import Provider from "./Provider";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie App",
  description: "Generated by Amann",
  icons: {
    icon: {
      url: "/vercel.svg",
      type: "image/svg",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Header />
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
